ALTER TABLE `Employee`
  ADD COLUMN `accrualMode` ENUM('STANDARD_TENURE', 'ADVANCED_TIER', 'MANUAL_ONLY') NOT NULL DEFAULT 'STANDARD_TENURE',
  ADD COLUMN `advancedAccrualTier` ENUM('YEARS_1_TO_5', 'YEARS_6_TO_10', 'YEARS_11_PLUS') NULL,
  ADD COLUMN `advancedAccrualEffectiveDate` DATETIME(3) NULL,
  ADD COLUMN `advancedAccrualReason` TEXT NULL;
